# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-19 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mdocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='murl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000)),
                ('doc_id', models.CharField(max_length=1000)),
            ],
        ),
    ]
